### ISSUE TITLE
Mixup between ARM64 and AMD64 in /ansible/tasks/setup-postgrest.yml

### ISSUE THREAD

**Issue by dazzag24** [supabase/postgres#115]
Is it just me or are these URLs the wrong way round in [setup-postgrest.yml](https://github.com/supabase/postgres/blob/develop/ansible/tasks/setup-postgrest.yml)

```
- name: PostgREST - download ubuntu binary archive (arm)
  get_url:
    url: "https://github.com/PostgREST/postgrest/releases/download/v{{ postgrest_release }}/postgrest-v{{ postgrest_release }}-linux-x64-static.tar.xz"
    dest: /tmp/postgrest.tar.xz
    checksum: "{{ postgrest_arm_release_checksum }}"
    timeout: 60
  when: platform == "arm64"

- name: PostgREST - download ubuntu binary archive (x86)
  get_url:
    url: "https://github.com/PostgREST/postgrest/releases/download/v{{ postgrest_release }}/postgrest-v{{ postgrest_release }}-ubuntu-aarch64.tar.xz"
    dest: /tmp/postgrest.tar.xz
    checksum: "{{ postgrest_x86_release_checksum }}"
    timeout: 60    
  when: platform == "amd64"
```
